"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { MAX_QUESTION_LENGTH } from "@/lib/constants";

type Message = {
  id: string;
  role: "user" | "assistant";
  text: string;
  isError?: boolean;
};

const GENERIC_ERROR = "Something went wrong. Please try again.";

function storageKey(listingId: string): string {
  return `property-qa:${listingId}`;
}

function loadMessages(listingId: string): Message[] {
  try {
    const raw = sessionStorage.getItem(storageKey(listingId));
    if (!raw) return [];
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter(isMessage);
  } catch {
    return [];
  }
}

function isMessage(value: unknown): value is Message {
  if (typeof value !== "object" || value === null) return false;
  const { id, role, text } = value as Record<string, unknown>;
  return typeof id === "string" && (role === "user" || role === "assistant") && typeof text === "string";
}

function saveMessages(listingId: string, messages: Message[]): void {
  try {
    sessionStorage.setItem(storageKey(listingId), JSON.stringify(messages));
  } catch {}
}

function nextId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function PropertyQA({ listingId }: { listingId: string }) {
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [hasLoaded, setHasLoaded] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setMessages(loadMessages(listingId));
    setHasLoaded(true);
  }, [listingId]);

  useEffect(() => {
    if (hasLoaded) saveMessages(listingId, messages);
  }, [listingId, messages, hasLoaded]);

  useEffect(() => {
    if (messages.length > 0 || isLoading) {
      bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
    }
  }, [messages.length, isLoading]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const trimmed = question.trim();
    if (!trimmed || isLoading) return;

    setMessages((current) => [...current, { id: nextId(), role: "user", text: trimmed }]);
    setQuestion("");
    setIsLoading(true);

    let reply: Message;
    try {
      const response = await fetch("/api/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ listingId, question: trimmed }),
      });
      const payload: { answer?: string; error?: string } = await response.json();
      reply =
        response.ok && typeof payload.answer === "string"
          ? { id: nextId(), role: "assistant", text: payload.answer }
          : { id: nextId(), role: "assistant", text: payload.error || GENERIC_ERROR, isError: true };
    } catch {
      reply = { id: nextId(), role: "assistant", text: GENERIC_ERROR, isError: true };
    }

    setMessages((current) => [...current, reply]);
    setIsLoading(false);
  }

  function clearHistory() {
    setMessages([]);
  }

  return (
    <section className="flex flex-col gap-4 rounded-xl border border-gray-200 bg-white p-4 sm:p-5">
      <div className="flex items-center justify-between gap-2">
        <div>
          <h2 className="text-lg font-semibold">Ask about this property</h2>
          <p className="text-sm text-gray-600">Answers are generated by an AI model from this listing&apos;s data only.</p>
        </div>
        {messages.length > 0 && (
          <button type="button" onClick={clearHistory} className="text-sm text-gray-500 hover:text-gray-900">
            Clear
          </button>
        )}
      </div>

      {(messages.length > 0 || isLoading) && (
        <ol className="flex max-h-[28rem] flex-col gap-3 overflow-y-auto pr-1">
          {messages.map((message) => (
            <li key={message.id} className={`message-enter flex ${message.role === "user" ? "justify-end" : "justify-start"}`}>
              <div
                className={`max-w-[85%] whitespace-pre-wrap rounded-2xl px-4 py-2.5 text-sm leading-relaxed sm:text-base ${
                  message.role === "user"
                    ? "rounded-br-sm bg-gray-900 text-white"
                    : message.isError
                      ? "rounded-bl-sm bg-red-50 text-red-800"
                      : "rounded-bl-sm bg-gray-100 text-gray-900"
                }`}
              >
                {message.text}
              </div>
            </li>
          ))}
          {isLoading && (
            <li className="message-enter flex justify-start">
              <div className="flex items-center gap-1.5 rounded-2xl rounded-bl-sm bg-gray-100 px-4 py-3" aria-label="Assistant is typing">
                <span className="typing-dot h-2 w-2 rounded-full bg-gray-500" />
                <span className="typing-dot h-2 w-2 rounded-full bg-gray-500" />
                <span className="typing-dot h-2 w-2 rounded-full bg-gray-500" />
              </div>
            </li>
          )}
          <div ref={bottomRef} />
        </ol>
      )}

      <form onSubmit={handleSubmit} className="flex flex-col gap-2">
        <label htmlFor="question" className="sr-only">
          Your question
        </label>
        <textarea
          id="question"
          value={question}
          onChange={(event) => setQuestion(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter" && !event.shiftKey) {
              event.preventDefault();
              event.currentTarget.form?.requestSubmit();
            }
          }}
          maxLength={MAX_QUESTION_LENGTH}
          rows={2}
          required
          className="w-full resize-none rounded-lg border border-gray-300 p-3 focus:border-gray-900 focus:outline-none"
          placeholder="Is this a good fit for a family with two kids?"
        />
        <div className="flex items-center justify-between gap-2">
          <span className="text-xs text-gray-500">
            {question.length}/{MAX_QUESTION_LENGTH} · Enter to send, Shift+Enter for a new line
          </span>
          <button
            type="submit"
            disabled={isLoading || question.trim().length === 0}
            className="rounded-lg bg-gray-900 px-4 py-2 text-white transition-opacity disabled:opacity-40"
          >
            {isLoading ? "Thinking…" : "Ask"}
          </button>
        </div>
      </form>
    </section>
  );
}
